version: '3.8'
services:
  db:
    image: postgres:15      # The SUBD/Librarian (PostgreSQL version 15)
    container_name: flowers_db
    restart: always
    environment:
      POSTGRES_USER: admin  # Your Database login
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: flowers_store_db # The name of your specific Database
    ports:
      - '5432:5432'         # "Open a door" from your Mac (5432) to Docker (5432)
    volumes:
      - postgres_data:/var/lib/postgresql/data # "Memory" - saves data even if Docker stops

volumes:
  postgres_data: